name: Deploy to Main

on:
  push:
    branches:
      - develop  # develop 브랜치에서 push가 발생할 때 트리거

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 전체 히스토리를 가져옵니다.

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 필요한 Node.js 버전을 설정하세요.

      - name: Install dependencies
        run: |
          cd practice-react1/shopping-site-1
          npm install

      - name: Build the project
        run: |
          cd practice-react1/shopping-site-1
          npm run build

      - name: Deploy to Main branch
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-username"
          git checkout main
          cp -R practice-react1/shopping-site-1/build/* .
          git add .
          git commit -m "Deploy build files from develop"
          git push origin main