name: Build and Deploy to Main

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 전체 기록을 가져옵니다.

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to main branch
        run: |
          git config --global user.email "yooralog@gmail.com"
          git config --global user.name "yoora"
          git checkout -B main
          find . -maxdepth 1 ! -name 'build' ! -name '.git' ! -name '.' -exec rm -rf {} +
          mv build/* . && rm -rf build
          git add .
          git commit -m "Deploy to main branch"
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
